### ISSUE TITLE
[feat]: Allow EmbassyOS users to create certificates using onboard certificate authority

### ISSUE THREAD

**Issue by cgalladora** [Start9Labs/start-os#1311]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

I would like to be able to create a certificate for other services using the onboard certificate authority

### Describe the Use Case

Suppose I have a router, ESXi server, or some other infrastructure in my environment. I'd like the CA that Embassy manages to be my one-stop-shop for certificates under my domain. This prevents me from having to run a parallel certificate authority for my other local infrastructure, or dealing with annoying "this site is insecure" warnings. In addition, I would then only have one root CA to add to my endpoints, rather than having to download another root CA to each of my endpoints to accommodate my other devices.

### Describe Preferred Solution

I'd rename "LAN Settings" to "LAN Management" and then have a button to create and sign a new certificate under the onboard certificate authority. 

### Describe Alternatives

Possibly create a new section called "Certificate Management" and place the root certificate download link there (only accessible via Tor of course).

**Comment by MattDHill** [comment]
Completed but still needs to be documented.
