### ISSUE TITLE
[feat]: display dependency opt-in and opt-out instructions in UI

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/start-os#1429]
The contents of `dependencies.<pkg-id>.requirement.how` in the manifest should be visible somewhere in the UI
<img width="562" alt="Screen Shot 2022-05-05 at 3 45 15 PM" src="https://user-images.githubusercontent.com/7445670/167022531-11f59899-c8eb-406c-9ecc-3797bc1c2177.png">

**Comment by MattDHill** [comment]
How is no longer a thing
