### ISSUE TITLE
[bug]: Docker Timeout

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1522]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

100

### Current Behavior

Docker Timeout seems to be the cause of the Photoview service mysteriously entering the "Stopping" state after no action by the user, and then getting stuck in that state.

### Expected Behavior

Services run continuously when no action is taken

### Steps to Reproduce

1. On services page
2. Find a service has gone into "Stopping" state, and become stuck there

**Comment by dr-bonez** [comment]
Matt thinks this is related to uninstalling

**Comment by dr-bonez** [comment]
However I have definitely seen this in many places where uninstalls were not involved

**Comment by kn0wmad** [comment]
I hit this on the latest Proxy update

**Comment by redragonx** [comment]
![image](https://user-images.githubusercontent.com/3073252/200925333-b9e1770b-c485-4b99-a906-8fbe84bb95d5.png)

**Comment by MattDHill** [comment]
035
