### ISSUE TITLE
[feat]: LAUNCH UI button with the ability to configure what URL it opens in a new window.

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/start-os#1568]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

On a service, the LAUNCH UI button could have the ability to open to <serviceaddress>.local , or you can configure it to open to <serveraddress>.local/admin/login - or whatever other folder structure you desire.

### Describe the Use Case

For wrapping services that already have the web server packaged up in a binary and cannot be changed without changing the upstream code. 

### Describe Preferred Solution

include a tag in the manifest that concatenates the default URL with a string value i.e. "/admin/login/".

**Comment by ProofOfKeags** [comment]
Concept ACK. this would also allow for devs to be able to autofill credentials through the get parameters if they want.

**Comment by ProofOfKeags** [comment]
it's service dependent, but no it is not limited to basic auth, any application can parse url parameters and treat them as possibly auth credentials.
