### ISSUE TITLE
[feat]: Transitive Auto-Configure

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/start-os#1601]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Allow a service to enforce requirements on a dependency of a dependency.

### Describe the Use Case

Specter depends on Bitcoin Proxy, Bitcoin Proxy depends on Bitcoin Core, Specter requires the underlying Bitcoin Core to have 4 RPC worker threads

### Describe Preferred Solution

Needs scoping

**Comment by elvece** [comment]
Will be unnecessary when #2050
