### ISSUE TITLE
[bug]: no way to exit out of config set errors, refresh required

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/start-os#1678]
Steps to reproduce:

1) Click save on invalid config
2) See error below:

<img width="875" alt="Screen Shot 2022-07-22 at 12 05 02 PM" src="https://user-images.githubusercontent.com/7445670/180489291-699c0ed3-8fbc-4da7-954c-55cd40605791.png">

3) Notice that there's no way to exit out of the error, no "x" button, ESC key does nothing. Only refreshing the page makes the error go away.

Suggested solutions:

Error boxes should have some way of clearing them, such as the ESC key or an "x" button in the top left or right corner

**Comment by MattDHill** [comment]
Hmmm I can't explain or reproduce this. Can you try again and gather more info from the console and network tab?

**Comment by chrisguida** [comment]
This is somewhat of an edge case. Right now it reliably happens when migrating a version of CLN where the config has `clboss` as a boolean to a version where `clboss` is a union of objects. Strangely, the error only occurs when i try to change from a boolean value to a union of `enabled`, which contains sub-keys. The error does *not* occur when I choose the `disabled` variant, which is an empty object with no subkeys. For some reason the frontend is fine with this. 

Console does not contain any errors, network tab has this result:

<img width="637" alt="Screen Shot 2022-07-25 at 2 40 17 PM" src="https://user-images.githubusercontent.com/7445670/180860904-9ea5ab72-0c69-4532-8147-1fc5a36c3621.png">

**Comment by MattDHill** [comment]
OK so there appears to be two different issues here. (1) the issue of a close button missing from the error toast and (2) you not being able to change the CLBOSS from a boolean to a union.

I think #2 is expected and probably should not be made to work. You should create a new key.

**Comment by chrisguida** [comment]
(2) is not the issue, I've talked to blu-j and discovered the problem.  But yes, (1) needs to be fixed.

**Comment by MattDHill** [comment]
Should be solved by new config module
