### ISSUE TITLE
[bug]: Unable to set up due to "Disk Management Error"

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1756]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

Disk Management Error File descriptor 9 (pipe:[14989]) leaked on pvremove invocation. Parent PID 594: /usr/local/bin/embassy-init File descriptor 10 (pipe:[14989]) leaked on pvremove invocation. Parent PID 594: /usr/local/bin/embassy-init WARNING: PV /dev/sda is used by VG EMBASSY_5PDBSFY6A43O5ISBKZYHTMOKXDJRFARE4L6AH5GJGULD2U3N5S5Q. WARNING: Wiping physical volume label from /dev/sda of volume group "EMBASSY_5PDBSFY6A43O5ISBKZYHTMOKXDJRFARE4L6AH5GJGULD2U3N5S5Q". Can't open /dev/sda exclusively. Mounted filesystem? Can't open /dev/sda exclusively. Mounted filesystem? Restart Embassy to try again.

Above error is given, restarts do not change the situation, error persists

### Expected Behavior

Setup flow completes

### Steps to Reproduce

1. Attempt setup flow
2. Get to 'add disk' stage
3. See error

**Comment by MattDHill** [comment]
Is this still a thing?

**Comment by kn0wmad** [comment]
To my knowledge it is unsolved, but has not been seen recently.  I think we started replacing hardware for these out of frustration

**Comment by kn0wmad** [comment]
I think @dr-bonez has more insight on this one

**Comment by dr-bonez** [comment]
For some reason lvm is automounting the disk, but not always. Trying to determine why

**Comment by redragonx** [comment]
https://github.com/systemd/systemd/issues/6066

https://unix.stackexchange.com/questions/348673/file-descriptor-leaked-on-lvchange-invocation-logical-volume-in-use

**Comment by MattDHill** [comment]
@dr-bonez status on this?

**Comment by dr-bonez** [comment]
Haven't reproduced in a while. It's hard to see what's causing the problem unless it can be reproduced in a lab

**Comment by MattDHill** [comment]
Closed as not recently reported
