### ISSUE TITLE
[feat]: Use OCI as default for packages instead of docker

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1774]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

OCI is an open standard and is compatible with docker, github, and podman.  This seems like a minimal lift and removes dependency on docker and more importantly, docker hub, for devs that wish to use existing images.

### Describe the Use Case

Decentralization and use of open protocols over proprietary companies' solutions

This also allows devs to host their images on GH or other platforms, and allows package devs to pull from those platforms into their wrappers

**Comment by didyktaras** [comment]
F

**Comment by didyktaras** [comment]
F

**Comment by kn0wmad** [comment]
> F

?

**Comment by kn0wmad** [comment]
As of v0.3.5, StartOS is now using Podman by default.  Additional OCI compatibility will come with v0.4.0.  Leaving open at this time.  Further testing will be required.

**Comment by EthnTuttle** [comment]
Has nix been considered?

**Comment by kn0wmad** [comment]
> Has nix been considered?

Yes.  It will not be used at this time.  Perhaps in the future.
