### ISSUE TITLE
[feat]: Better developer tooling to improve the health check experience for users

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1780]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Namely, timeliness - for example, a UI may be available long before the health check indicates that this is the case

### Describe the Use Case

Improved UX

**Comment by chrisguida** [comment]
@Blu-J's filebrowser and syncthing healthchecks were designed to solve this i believe.

**Comment by kn0wmad** [comment]
Should this ticket be moved to https://github.com/Start9Labs/embassy-sdk-ts/ ??
