### ISSUE TITLE
[feat]: Image carousel for service UIs in marketplace

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#1815]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Add a section to the top of a service's marketplace show page that optionally displays images of the service's UI in a sliding / toggle carousel.

Approx 4::3 content ratio - display 3-4 in a grid row. Images can be clicked to enlarge.

### Describe the Use Case

This is useful so that users can make a more informed choice about installing a particular service based on its user interface, especially for applications that serve similar purposes (eg. RTL and Thunderhub)

Also provides a nice visual component to the marketplace show pages in addition to the informative text.

**Comment by MattDHill** [comment]
This will be handled by the brochure marketplace
