### ISSUE TITLE
[feat]:  `embssy-sdk init` output file location on success

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1854]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Currently returns nothing

### Describe the Use Case

self-explanatory

**Comment by chrisguida** [comment]
...what is this?

**Comment by kn0wmad** [comment]
I don't know how else to explain this - Can be re-assigned to me if necessary

**Comment by kn0wmad** [comment]
Nothing - that's the whole point

**Comment by chrisguida** [comment]
You mean you want it to output the config file location?
