### ISSUE TITLE
[feat]: Service action that creates a new Tor and/or LAN address

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/start-os#1904]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

This would generate a new Tor address and/or LAN address without requiring an uninstall/reinstall of the service.

### Describe the Use Case

Sometimes addresses get exposed and it's not harmless when they do. Especially for services with no authentication like mempool where if anyone learnt your Tor address they could just use it willy-nilly.

Uninstalling and reinstalling the service could be highly undesirable making the person choose between two bad choices - reinstalling and having to set everything up again/recover data they might not have VS just hoping no one learns their service Tor address or uses it maliciously/against the will of the user.

**Comment by MattDHill** [comment]
related #2054

**Comment by MattDHill** [comment]
Will be handled by general OS networking features in 040
