### ISSUE TITLE
[feat]: Multi-Container Support

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1943]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Self-explanatory, making this issue as I couldn't find one that had been made yet

CC @Blu-J 

### Describe the Use Case

Allows more complex services, such as the Dojo Stack

**Comment by kn0wmad** [comment]
I don't recall, was this slated for v040?  I noticed it has no milestone atm

**Comment by MattDHill** [comment]
It is not

**Comment by 2Fast2BCn** [comment]
So I guess it will never be possible?
