### ISSUE TITLE
[fix] resolve 2038 NTP bug

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#1971]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

6.0

### Browser

Firefox

### Browser Version

102

### Current Behavior

Time defaults to the year 2061 for reasons unknown.  Timedatectl is unable to get a response from NTP servers, even when added manually.  @dr-bonez is familiar

### Expected Behavior

Timedatectl syncs to NTP server

### Steps to Reproduce

1. Setup embassyOS
2. You'll know you hit it because nothing that needs a cert works

**Comment by elvece** [comment]
Related https://github.com/Start9Labs/embassy-os/issues/267

**Comment by MattDHill** [comment]
- If date is > 2038, set date to hardcoded date.
- If NTP does not sync after 60 seconds, issue notification
