### ISSUE TITLE
Refactor how service status is reported in the OS

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/start-os#2065]
Currently we conflate 2 different ideas:
  - The user's desired service status (running/stopped/restarting)
  - The services actual status (running/stopped/restarting)
The service needs to report it's actual status to the os, such that if it needs to restart internally, as a result of an action, or saving config, it can say so.

Using these 2 statuses, we can communicate the information to the user using the following matrix:
| desired | actual | displayed |
| ------- | ------- | --------- |
| running | running | running |
| running | stopped | starting |
| stopped | running | stopping |
| restarting | * | restarting |
| * | restarting | restarting |

**Comment by MattDHill** [comment]
service running status should list health checks that it will run

**Comment by MattDHill** [comment]
Can this be closed @dr-bonez ?

**Comment by dr-bonez** [comment]
This is addressed in the integration/refactors branch which hasn't been merged

**Comment by MattDHill** [comment]
035
