### ISSUE TITLE
[feat]: Better messaging around e2fsck upon eOS setup

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/start-os#2082]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

When people flash or ota upgrade eOS, there can be long periods of waiting during setup with no real feedback to let the user know what's happening.  One likely culprit is e2fsck detecting errors on the target filesystem and attempting to correct them.

When this happens, things can stall out for a long time with no feedback to the user.  We need better messaging when this happens (and preferably options to stop/abandon the process if it's taking too long).

### Describe the Use Case

The user will know better what's actually happening / taking so long.

### Describe Preferred Solution

Better messaging around e2fsck actions.

### Describe Alternatives

Perhaps if errors are detected, and a simple overwrite would take care of them, we can give the user an option to 'repair or don't care'?

Maybe there's something more modern / different approach than e2fsck?

**Comment by MattDHill** [comment]
solved by progress bars and messaging in init UI
