### ISSUE TITLE
[bug]: CLN health checks say container is paused while still running (currently file browser is backing up)

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/start-os#2094]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Firefox

### Browser Version

108.1

### Current Behavior

![image](https://user-images.githubusercontent.com/45926711/209877299-ca663aca-f8ed-48ca-945c-99c08afed208.png)

### Expected Behavior

The health check should correctly report that CLN is actually running because it is.

This may resolve itself once the backup is complete - will know in a few hours.

### Steps to Reproduce

Not sure yet, I just did a regular backup with CLN installed as one of my services.

### Anything else?

Bitcoin, Proxy, and CLN were all done with backups, but CLN remained in this state indefinitely while File Browser was backing up,

AFAICT CLN is running due to the fact that stuff is happening in logs and RTL reports all channels as being open and active.

**Comment by BitcoinMechanic** [comment]
Update: after file browser finally finished its backup (while other services remained backing up) it resolved.

**Comment by chrisguida** [comment]
How long was it like this? Hcks run once a minute, I think.

**Comment by BitcoinMechanic** [comment]
multiple hours - it only resolved once file browser finally finished

**Comment by chrisguida** [comment]
@dr-bonez @Blu-J any ideas on this? This doesn't seem like a problem with the hck itself

**Comment by dr-bonez** [comment]
Yes this seems like a bug with the backup flow
