### ISSUE TITLE
[bug] 'Timeout' leads to disconnection

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2096]
Embassy Pro - unknown the relevance of each below error:

ERROR: Embassy:manager: service crash KILLED

synchronizer for Ride the Lightning failed

0: Timeout error
embassy:manager:exit
::::empty
::::shutdown

**Comment by dr-bonez** [comment]
might be fixed by adding sysbox
might be fixed by removing bollard
