### ISSUE TITLE
[bug]: "RPC ERROR: Incoherent Could not find" upon pressing buttons in the UI

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/start-os#2114]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

v0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5

### Browser

Firefox

### Browser Version

108

### Current Behavior

When have Bitcoin stopped, then install fulcrum from alpha and either 
1) configure fulcrum to use Bitcoin Core, then attempt to Start Bitcoin Core, I get this "Incoherent" error:
![image](https://user-images.githubusercontent.com/106188942/211960834-8b477ef7-838d-497d-b80d-42b7957a6833.png)

OR

2) configure fulcrum to use Bitcoin Proxy, then attempt to add fulcrum credentials to Bitcoin Proxy, and hit Save, I get this error:
![image](https://user-images.githubusercontent.com/106188942/211960737-7212e0b5-d982-4a53-a568-1e34a3bb916a.png)

### Expected Behavior

I expect buttons I click to work and to receive no errors.

### Steps to Reproduce

1. Stop Bitcoin Core [Prod]
2. Install fulcrum from Alpha
3. Configure it to use Bitcoin Core (or bitcoin proxy -- prod)
4. Hit START-> on the Fulcrum page's suggestion to start bitcoin core (if you chose Bitcoin Core) and attempt to Start bitcoin core, or add fulcrum's credentials to Bitcoin Proxy, using the Fulcrum page's suggestion to AUTO CONFIG-> then hit Save
5. See [RPC ERROR: Incoherent Could not find] error box pop up in the top right hand corner

**Comment by MattDHill** [comment]
fixed in 035
