### ISSUE TITLE
[bug]: RPC ERROR: Disk Management Error Device wipe error, offset 0. Cannot wipe header on device /dev/EMBASSY_**/main. Restart Embassy to try again.

### ISSUE THREAD

**Issue by P-Verbrugge** [Start9Labs/start-os#2149]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

13.2

### Browser

Safari

### Browser Version

16.3

### Current Behavior

Trying to setup Start9/Embassy but I keep getting disk errors:

> [bug]: RPC ERROR: Disk Management Error Device wipe error, offset 0. Cannot wipe header on device /dev/EMBASSY_**/main. Restart Embassy to try again.

The problem only occurs with my MX500 1TB SSD (M3CR033). I tested it what an BX500 120GB and the problem does not occur with that drive. The SSD is working just fine. Tested the drive with the software of Crucial. It has not errors and the firmware is also up-to-date.

I tried two controllers. A jMicron and Sabrent. In both cases the BX500 works, but the MX500 doesn't. I formatted the drive multiple times. Even re-partitioned the drive as well. No luck. Al formatting and repartitioning is done on MacOS. The drive check is done on Windows.
Also with Raspiblitz, Umbrel and Sentinel the drive works fine and does its job.

My hardware:
Raspberry Pi 4 + 4GB memory
Official Raspberry Pi Powersupply
SSD: Crucial MX500 1TB

### Expected Behavior

I would expect the drive to be formatted correctly and work like it does with other software too.

### Steps to Reproduce

Install Embassy OS on an SD card
Add a Crucial MX500 1TB ssd to the USB 3 port of the pi
Use the official power supply of a raspberry pi

Try to do the setup of Embassy OS. After selecting the drive and trying to format the drive, the system gives errors.

### Anything else?

I do notice that it takes a really long time (couple of minutes) for the drive to show up as the data storage drive during setup. I don't know if this is normal behavior.

**Comment by dr-bonez** [comment]
I recommend using a larger power supply. The official pi power supply is insufficient for full speed use of an external drive.

**Comment by MattDHill** [comment]
Not reported in a while, likely Pi power supply-related
