### ISSUE TITLE
[bug]: Unable to Resolve mDNS v4

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2154]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

6.0

### Browser

Firefox

### Browser Version

102

### Current Behavior

Attempt to connect to https://embassy-unique-id.local and get "Unable to connect" - mDNS is not resolving.

This happens on Embassy One and Embassy Pro

`avahi-resolve-host-name -4 embassy-unique-id.local`
`Failed to resolve host name 'embassy-unique-id.local': Timeout reached`

However, resolving IPv6 works.  This is not enough to resolve in the browser.  Investigating in Embassy revealed that the bridge interface was the one being resolved by avahi on eOS, however changing that to the eth0 interface did not fix the problem.

### Expected Behavior

Resolve `.local` address in browser (and terminal)

### Steps to Reproduce

Described above

**Comment by MattDHill** [comment]
If more info present, we can re-open
