### ISSUE TITLE
[feat] Replace Audio Feedback For Hardware Simplicity

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2164]
Ideas welcome

- RGB LED Feedback?

**Comment by MattDHill** [comment]
Anything hardware related will leave us in the same place we are now with the speaker. Audio feedback will be made redundant by user interface enhancements

**Comment by kn0wmad** [comment]
Ticket can be changed to "Deprecate"

**Comment by chrisguida** [comment]
UI can't completely replace audio feedback. We'd need something to indicate that the UI is ready to visit upon setup.

**Comment by MattDHill** [comment]
Not sure what you mean. Setup is done through a UI

**Comment by chrisguida** [comment]
Yes, I'm referring to before embassy.local is ready. The chime helps the user know when embassy.local is ready to visit.

**Comment by MattDHill** [comment]
Related #2167

**Comment by MattDHill** [comment]
Handled by Init UI and restarting/shutting-down states
