### ISSUE TITLE
[feat]: Refactor FE Projects + Preloading

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#2175]
In the current system, we indicate that the system is initializing with a "bep" sound and that this process has been completed with a "chime" sound from the hardware device. We want to move away from depending on audio feedback so we can support a larger set of hardware devices, and generally improve the simplicity of the hardware building process.

In order to remove audio feedback, we need a way to provide user interfaces while the device is initializing. As such, we have scoped out adding an additional interface called the `init-ui` that will display during the initialization period (between "bep" and "chime"). Adding an additional UI promoted a refactor of the way UI's are served from the backend, and thus a restructuring of the frontend projects.

The relevant frontend projects are listed below. The backend currently serves only one of these interfaces at a time.
- `install-wizard`
- `setup-wizard`
- `diagnostic-ui`
- `ui`

Now, the frontend should be split into the following groups:
- `install-wizard`
- `setup-wizard`
- main (`init-ui` **_new_**, `diagnostic-ui`, `ui`)

The backend will serve interfaces in these phases:
1. The `install-wizard `(`embassy.local`)
2. The `setup-wizard` (`embassy.local`)
3. All Main interfaces (`init-ui`, `diagnostic-ui`, `ui`) (`adjective-noun.local`)

The following user flows exists:

Install & Setup:
`install-wizard -> setup-wizard -> main (init-ui) -> main (ui)`

System reboot and system rebuild:
`main (init-ui) -> main (diagnostic-ui) || main (ui)`

---

This refactor influences the preloading strategy. Since we will be serving all Main interfaces at once, we need to prioritize component loading. 

1. The `init-ui` will always display first, these components should always be the first to load. 
2. `ui` - menu / connection component
3. `ui` - service list page
4. `ui` - service show page
5. `ui` - marketplace
6. `ui` - updates
7. `ui` - system page
8. `ui` - notifications
9. `diagnostic-ui` - this will display least often

**Comment by elvece** [comment]
Related: 
- https://github.com/Start9Labs/embassy-os/issues/2164
- https://github.com/Start9Labs/embassy-os/issues/2167

**Comment by waterplea** [comment]
Diagnostic UI is a separate app. And so Init UI, from what I understood. It means they are irrelevant in the preloading question. I also have been looking into priority loading of the routes and it seems to me at this point that PreloadingAllRoutes is enough — right now lazy routes are very small and the problem is in the big main bundle. I will roll out a PR today partly dealing with this issue.

**Comment by MattDHill** [comment]
The plan is to combine the init UI, Diagnostic UI, and Main UI into a single project. This way, following initialization, we can simply route the user to diagnostics or main without having to refresh the page and begin the loading process all over again. The is especially important over Tor.

**Comment by waterplea** [comment]
Ok, got it 👍 then I'll keep on working on prioritized preloader.
