### ISSUE TITLE
Implement RClone with filename compression

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/start-os#2190]
We have ran into issues where rsync when going to MS or mac filesystems, we have following issues:
1. Permissions
2. Long file names
3. Path too long

RClone hints at these issues in their encryption docs, there are several bug that was solved with an experimental feature.
We could also write a fuse layer to solve this too with tar each file + path

**Comment by MattDHill** [comment]
Related #2362

**Comment by MattDHill** [comment]
Using our own fuse module instead
