### ISSUE TITLE
[bug?] Addresses Resolving with Auxilary Suffixes

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2206]
Bitcoin LAN address resolved to an ipv6 ip address which returned with a `%28` suffixed.  No ipv4 address was returned either.

"Either this is a red herring and weird way things are displayed or we really have a bug in the ipv6 address going into services' .local names" - @gStart9

**Comment by MattDHill** [comment]
red herring, just a weird display
