### ISSUE TITLE
[bug?] Some Hardware Treats `/sys/class/thermal/thermal_zone0/temp` Differently

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2207]
E2 prototype shows extreme cold temps on this sensor.  This could also be a problem with this particular hardware/firmware.

Perhaps there is a better way to handle temp sensors?  There are other sensors available on this device that show what are probably accurate temps (obviously in different locations).

Relevant eOS code:

https://github.com/Start9Labs/embassy-os/blob/8ffcd9b60a6799bbb522c53a8cdad10dc711935f/backend/src/system.rs#L515

**Comment by kn0wmad** [comment]
Some DIY folks are getting errors in relation to this, obviously their hardware is producing chip temp data elsewhere

`ERROR embassy::system: Could not get initial temperature: Filesystem I/O Error: /sys/class/thermal/thermal_zone0/temp: No such file or directory (os error 2)`

**Comment by stupleb** [comment]
Possibly related on DIY build...

v0.3.4.1 – Reported temperature worked just fine, with ranges of 80ºc to 100ºc under heavy load.
v0.3.4.2 – Temperature wildly misreported with values of 1990ºc to 2200ºc under heavy load.

Hardware:
https://support.apple.com/kb/SP659?locale=en_US

**Comment by MattDHill** [comment]
using LMsensors now, should resolve.
