### ISSUE TITLE
[feat] Drive Mounting Tool

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2223]
For inspecting backups, for example

**Comment by chrisguida** [comment]
omg yes

**Comment by chrisguida** [comment]
This is for mounting the embassy drive, correct? so cifs drives would be different? or is this just a request for both?

**Comment by kn0wmad** [comment]
> This is for mounting the embassy data drive, correct? so cifs drives would be different? or is this just a request for both?

Now that you mention it... Both

**Comment by JenJenJay35** [comment]
`[ecece11bae743d25d796e979c09b1dc9a95c4b3bad159280db958544a369 7a7c]() `

**Comment by kn0wmad** [comment]
Feature added in v0.3.4.3
