### ISSUE TITLE
[feat]: cli or gui based utility which verifies correct firmware is install on the Embassy Pro

### ISSUE THREAD

**Issue by tinysound464** [Start9Labs/start-os#2245]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Given that some Embassy Pro's went out the door with incorrect firmware, adding a feature within Embassy OS (be it a CLI utility or part of the Web GUI) should be available in order to verify correct firmware is installed.  It would also be nice if this tool advised there is newer Start9 approved firmware available. 

### Describe the Use Case

Given that some Embassy Pro's went out the door with incorrect firmware, adding a feature within Embassy OS (be it a CLI utility or part of the Web GUI) should be available in order to verify correct firmware is installed.  It would also be nice if this tool advised there is newer Start9 approved firmware available. 

### Describe Preferred Solution

Add a feature to the OS in order to verify firmware validity. 

### Describe Alternatives

N/A

**Comment by MattDHill** [comment]
Only for server Pure:

Using `start-cli server update-firmware` will be a no-op if the correct and most recent firmware is installed. Otherwise it will update to the latest.

This also runs on every boot, checking against the firmware that is already included in the OS image.
