### ISSUE TITLE
[bug]: UI distorted after locking and unlocking screen

### ISSUE THREAD

**Issue by Dominion5254** [Start9Labs/start-os#2256]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.4.1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Ventura 13.3.1

### Browser

Firefox

### Browser Version

112.0.1

### Current Behavior

The UI of the current open page is distorted (stretched out) after unlocking computer.

I haven't been able to reliably reproduce this bug, but it seems to present after locking and unlocking the screen for an indeterminate amount of time. A refresh of the page returns the page to normal proportions.

The below screen clippings are the entire page as displayed on the monitor.

![ui_bug_1](https://user-images.githubusercontent.com/125493428/234404872-fc5d8ce5-1c35-449f-8bd8-a05c1efcd6fc.png)
![ui_bug_2](https://user-images.githubusercontent.com/125493428/234404878-480f8c33-bff2-436d-9754-69047f2eacb7.png)

### Expected Behavior

UI renders with normal proportions. 

### Steps to Reproduce

1. Open any page of the Start9 UI.
2. Lock computer screen for an indeterminate amount of time.
3. Unlock computer and (possibly) observe UI distortion.

**Comment by Dominion5254** [comment]
> Does this happen exclusively on a Linux machine? Are you using multiple monitors by chance?

I have only encountered this on a mac with an additional monitor so far.

**Comment by MattDHill** [comment]
Closing until recurrance in 040 UI
