### ISSUE TITLE
[feat]: Add a UI to the Start9 registry link

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/start-os#2305]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

Links to the marketplaces i.e. https://community-beta-registry.start9.com display a not found error when viewed via a standard browser instead of selected as marketplace in the change registry section of StartOS.  Currently the marketplace URL returns:

`<!DOCTYPE html>`
`<html><head><title>Not Found</title></head><body><h1>Not Found</h1>`
`<p>/</p>`
`</body></html>`

Please add a UI so opening the URL in a standard browser returns useful information.

### Describe the Use Case

This is helpful in cases where the registry URL is posted / sent and someone else opens the URL in a browser instead of in StartOS Add Custom Registry.  

### Describe Preferred Solution

There should be a configuration in the Marketplace setting that returns useful information.  It would be nice if marketplaces could automatically display what services are in them.  For example:

If I go to https://registry.start9.com it could automatically display something like https://marketplace.start9.com/marketplace displays today instead of the Not Found as described above.

And if I go to https://community-beta-registry.start9.com it displays the same UI, but shows the services available within that marketplace.

### Describe Alternatives

Have UI display a configurable HTML message.  Here is a first draft default message with a proposed link to a picture to include:

The URL https://community-beta-registry.start9.com is designed to be opened within the StartOS marketplace configuration page.  To access this marketplace, go to the Marketplace tab and click on CHANGE and enter the URL there.  
<[PICTURE](https://docs.start9.com/latest/_images/markettab.png)>

Here are some links that may be useful:
- More information on Start9 Marketplaces is available at: https://docs.start9.com/latest/user-manual/dashboard-overview#marketplace-tab
- Frequently Asked Questions: https://docs.start9.com/latest/support/faq/ 
- More information on StartOS is available at: https://start9.com/

**Comment by kn0wmad** [comment]
I think this issue will need to be transferred to the registry or website repos.  Perhaps it could be lumped in with https://github.com/Start9Labs/start9.com/issues/17
