### ISSUE TITLE
[feat]: App

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [Start9Labs/start-os#2307]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

Running PyBLOCK using Docker
First check out or [unzip](https://github.com/curly60e/pyblock/archive/refs/heads/master.zip) the code to a directory, cd to that directory, and from there type the following commands: (Make sure Docker desktop is running in the background "sudo service docker start".)

docker build -t pyblock .
Run it using

docker run -p 6969:6969 -it pyblock
Then open http://localhost:6969/ with a browser, you will get the PyBLOCK Docker App.

Credentials: "Running:PyBLOCK" ("User:Pass")

### Describe the Use Case

App

**Comment by kn0wmad** [comment]
This repository is only for our Operating System.  You may get dev attention for services by posting them on the [unofficial feedback forum](https://embassyos.fans/), or on the [Community Hub](https://community.start.com).  For our general strategy regarding services, please read this [blog post](https://blog.start9.com/start9-marketplace-strategy/).
