### ISSUE TITLE
[feat]: Secure Initial Setup / Connection Bootstrapping

### ISSUE THREAD

**Issue by AndySchroder** [Start9Labs/start-os#2317]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

Initial setup of start9 is pretty insecure. We are supposed to plug into ethernet and then anyone on the local network can go to a http server and setup the initial password. Then, we are supposed to download a self signed SSL certificate over that http connection. Nothing about this makes sense for a system that we expect to provide us security of our data if the system can be compromised at the very beginning.

### Describe the Use Case

See Above

### Describe Preferred Solution

A few possible options. Implementing one or all of them would be good.

1. Require plugging into an HDMI monitor or provide hardware with a built in screen (like http://andyschroder.com/DistributedCharge/news/2022.06.04-RaspiBlitzOnTheTOFU/) to present a QR code of some kind that can be used to securely boostrap the connection. https://github.com/LN-Zap/lndconnect/blob/master/lnd_connect_uri.md is a good example of how to present a host and SSL certificate in a single string that could be placed inside a QR code.
2. Require using a USB disk that is shuffled between the start9 machine and the users computer that contain the credentials.
3. Allow plugging in a USB ethernet adapter to the start9 machine (so that it has a second ethernet adapter) so that the user can plug their laptop directly into the start9 machine and do the configuration over http on a separate 2 machine LAN without any other hardware being able to sniff or MITM the traffic or set a different password first. Alternatively, you could use the USB-C ethernet gadget mode on the raspi4 (https://forums.raspberrypi.com/viewtopic.php?t=245810) instead of a USB to ethernet adapter.

**Comment by kn0wmad** [comment]
Thanks for the suggestions!  Keep in mind that our mission is to make it as easy as possible to run a server, with minimal compromise.  One of the most difficult problems is the initial setup.  We wanted to enable SSL, but we also wanted to have the notion of "plug-n-play" for non-techie users.  The most secure initial setup would be via 'kiosk mode,' which is provided when you plug in a monitor, and keyboard/mouse to your server (x86_64 only at this time), but we could additionally provide a better way to transport the cert to your clients.

We are constantly improving this process and your input is very valuable.  We will look into your options.

**Comment by AndySchroder** [comment]
OK, kiosk mode may be much simpler then. I recall now that in https://github.com/Start9Labs/start-os/issues/2143 you say kiosk mode is turned off by default on the raspi4. Perhaps make it required to use kiosk mode on all platforms to do initial setup, but on the raspi4 if you are worried about firefox using too much ram, disable kiosk mode after initial setup is complete.

**Comment by dr-bonez** [comment]
We do not plan on requiring kiosk mode for setup given that we anticipate that the convenience of LAN setup is worth it if your threat model doesn't include a targeted spoofing attack from an attacker with access to your lan at the time of setup. Such an attacker would have to anticipate the device being set up and perform an MITM attack designed specifically to compromise the start-os server. This is an attack vector that cannot be protected against without a keyboard/monitor, which many users may not have access to. We do, however, protect against non-targeted snooping attacks by encrypting the password in transit. If a targeted MITM spoofing attack is a possibility for you, we do recommend kiosk mode.
