### ISSUE TITLE
[bug]: wifi does not work on the raspberry pi compute module 4 (CM4)

### ISSUE THREAD

**Issue by AndySchroder** [Start9Labs/start-os#2318]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### StartOS Version

0.3.4.2

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

N/A

### Browser

Firefox

### Browser Version

N/A

### Current Behavior

Wifi does not work on the raspberry pi compute module 4. Going through the web based setup, I get an error message:

`RPC ERROR: WiFi Internal Error wlan0: ERROR while getting interface flags: No such device`

### Expected Behavior

1. Wifi works and it allows me to set everything up.
2. Wifi doesn't work and it still allows me to set everything up via ethernet.

### Steps to Reproduce

1. Image a CM4 with start9
2. boot
3. try to setup start9
4. error comes up after setting your password.

### Anything else?

Solution:

```
sudo /usr/lib/embassy/scripts/chroot-and-upgrade
cd /usr/lib/firmware/brcm/
ln -s brcmfmac43455-sdio.raspberrypi,4-model-b.txt brcmfmac43455-sdio.txt
exit
```

I'm not sure if this is the best way to fix the problem, but it works for me.

Alternatively, I can also run
```
sudo /usr/lib/embassy/scripts/chroot-and-upgrade
apt update
apt install firmware-brcm80211
exit
```
and that also works.

Also, this issues suggests that all raspi are not created equal: https://github.com/geerlingguy/pi-router/issues/4 . There may be more things that should be done to make reliable wifi on all raspi.

**Comment by dr-bonez** [comment]
firmware-brcm80211 is already included in our raspberry pi image. Are you using the latest raspi image?

**Comment by AndySchroder** [comment]
I just tried again with the new release that you published a few hours ago. It works! If only I would have waited a few days to have tried this........
