### ISSUE TITLE
[feat]: Allow for adding network folder by IP as well

### ISSUE THREAD

**Issue by vindard** [Start9Labs/start-os#2335]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

I'd like to be able to mount a network folder based directly on the IP of the device that network folder is hosted on. It looks like it's only possible to do this by name when trying to mount a folder for backups for the current interface.

### Describe the Use Case

Mounting folders in networks where hostnames may not be unique or consistent.

### Describe Preferred Solution

I believe this function needs to be expanded for nmblookup to take an -A argument with the ip address (from terminal `$ nmblookup -A <my-ip>` works in place of `$ nmblookup <hostname>`)
https://github.com/Start9Labs/start-os/blob/bada88157e53b64fe7fa1bceef9739b198ae1d54/backend/src/disk/mount/filesystem/cifs.rs#L18

**Comment by kn0wmad** [comment]
This is closed by #2347
