### ISSUE TITLE
[bug]: Unable to refresh StartOS PWA on iOS

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/start-os#2351]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Rpi4 and Pure

### StartOS Version

0.3.4.3

### Client OS

iOS

### Client OS Version

16.5.1

### Browser

Safari

### Browser Version

16.5.1

### Current Behavior

The current behavior for refreshing PWAs on mobile devices, specifically iOS, presents challenges and lacks user-friendly solutions. Removing the StartOS PWA icon from the home screen and reading it is an inelegant workaround.
After and OS update user is always presented with this popup:
![IMG_6918](https://github.com/Start9Labs/start-os/assets/3606313/be28673e-5f6a-4ee0-b81f-2076a862ebcb)

### Expected Behavior

I propose implementing an enhanced PWA refresh experience that overcomes these limitations. This can be achieved through:

- Integration of a Reload Button: I suggest adding a reload button within the popup notification, providing users with a simple and intuitive way to trigger a content refresh. This would streamline the process and improve the overall user experience.

or

- Automatic Cache Update: Cool feature would be the ability to automatically detect when the page cache needs updating. By enabling automatic cache updates behind the scenes, users would always have access to the most up-to-date and accurate content without requiring manual intervention.

### Steps to Reproduce

1. Add StartOS PWA as a bookmark in Home Screen
2. Update StartOS to a newer version
3. Open StartOS bookmark from the Home Screen

### Anything else?

By implementing these enhancements, we can eliminate the complexities associated with PWA refresh on mobile devices, providing a more seamless and user-friendly experience for StartOS users.

**Comment by elvece** [comment]
To my knowledge, it is unfortunately not currently possible to programmatically hard refresh. Its expected that any changes to the files will be detected by the service worker and update what is cached accordingly, but we might need to more specifically trigger this event. Will investigate.

**Comment by k0gen** [comment]
Adding some video context to the mix:

https://github.com/Start9Labs/start-os/assets/3606313/4c18d11c-d1fc-4ccf-bd1c-899824f5d91d

**Comment by k0gen** [comment]
> To my knowledge, it is unfortunately not currently possible to programmatically hard refresh. Its expected that any changes to the files will be detected by the service worker and update what is cached accordingly, but we might need to more specifically trigger this event. Will investigate.

Ohhh I see it, the [Background Sync API](https://caniuse.com/?search=background%20sync) is not an option on Safari :(

It seems like having the refresh button as an option will be a suitable approach for now.
