### ISSUE TITLE
[feat] Shorten the Length of Backup Dir Names

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2362]
This causes some problems with integrations, for example, Synology devices enforce a character limit of 143 characters.  I thought there was a ticket for this already, but could not find it.  Apologies if duplicate or invalid

**Comment by Schilling1198** [comment]
I have also run into issues with the length of the Backup Directory on a Windows Machine, and would like to see if shortened
![Too Long 2](https://github.com/Start9Labs/start-os/assets/171931488/2ea78d52-89f1-47e2-b6d4-154e6fb4465c)

**Comment by MattDHill** [comment]
Solved by start-fs fuse module.

**Comment by Schilling1198** [comment]
> Solved by start-fs fuse module.

Would you mind explaining a little bit more for us less tech savy? lol. Is the fix in an upcoming release of StartOS?
