### ISSUE TITLE
[bug]: Password Length Constraints Are Different Between Setup And Login Pages

### ISSUE THREAD

**Issue by techrivertree** [Start9Labs/start-os#2375]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Pi Model 4B 8GB

### StartOS Version

0.3.4.3

### Client OS

Linux

### Client OS Version

Ubuntu 22.04

### Browser

Firefox

### Browser Version

115.0.02

### Current Behavior

After saving new login info, I cannot set a new password for my new install. I tried eleven different password ranging in length from 6 to 64 with all different kinds of letters and numbers. Nothing world work.

### Expected Behavior

Accept a new password that is 64 characters on less in lenght.

### Steps to Reproduce

Setup new install and try to set a new password.

### Anything else?

I searched for StartOS password requirements but I could not find anything.

**Comment by MattDHill** [comment]
Hi @techrivertree can you clarify? Are you saying you are unable to set up a fresh StartOS server? Or are tou trying to change your password for a previously set up device?

What error are you seeing?

**Comment by techrivertree** [comment]
@MattDHill New install. 

Its the startOS login page. It prompts me to enter in a password (for the first time) but it wont accept any password that create, from super simple to super complex

**Comment by techrivertree** [comment]
I will try a reinstall.

I can enter in passwords, it just wont accept anything. The only requirement I know of is a character limit of 64 characters.

**Comment by kn0wmad** [comment]
As Matt said - we would need more details - what EXACTLY is happening?   "Won't accept anything" doesn't give us anything to look at or help you with

**Comment by techrivertree** [comment]
Its working now. 

The bug is with the first password you setup. I was able to use a super complex 192 character password. When you start your new custom login page, the password is too long (max 64 characters).

Fix: Either change the password requirements for the first password or fix the password requirements for new start page.

**Comment by kn0wmad** [comment]
Okay, I'm going to change the title to reflect that this is a real bug.  Thanks for reporting

**Comment by jadijadi** [comment]
As @kn0wmad already said, the root cause is having the maxlength=64 during the setup-wizard but not having it in the login page. So if you copy paste a long password into the fields, they will be different when being checked. Tested this on my VM and as a workaround you can login using only the first 64 characters of your password.

Sent PR #2394 as a permanent fix.
