### ISSUE TITLE
[bug]: Start login?

### ISSUE THREAD

**Issue by mastakalandir** [Start9Labs/start-os#2377]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Pi 4 (8gb) with 128gb microSD

### StartOS Version

0.3.4.3

### Client OS

Other

### Client OS Version

Raspbian

### Browser

Firefox

### Browser Version

NA

### Current Behavior

On a Raspi 4, flashed StartOS but I get start on first boot with a login and I can't find credentials for this anywhere.

Followed this document: https://docs.start9.com/latest/user-manual/flashing/flashing-pi

After initial boot with the StartOS flashed MicroSD, the Pi turns on the show some terminal messages going by, then I meet with login text on the top left of screen as:
"Debian GNU/Linux 11 start - 
start login: "

Tried several random credentials, treating it as an account setup but I always received "Login incorrect". 

### Expected Behavior

Not asking for login credentials at first boot.

### Steps to Reproduce

Follow every step here until 7) https://docs.start9.com/latest/user-manual/flashing/flashing-pi
Then power up Pi.

### Anything else?

![WhatsApp Image 2023-07-28 at 11 20 50 PM](https://github.com/Start9Labs/start-os/assets/140868574/549d42e0-1d68-4946-9905-cd582bb9586d)

**Comment by kn0wmad** [comment]
Please follow the [Initial Setup Guide](https://docs.start9.com/latest/user-manual/initial-setup) and visit http://start.local to set up and access your device.  No set of credentials will work on this screen.  If you have any issues, please ask in our [support channels](https://start9.com/contact).
