### ISSUE TITLE
[bug]: EmbassyOS Update Failed

### ISSUE THREAD

**Issue by Ven0r** [Start9Labs/start-os#2387]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Pi 4b 8gig / 64gb HE SD/ 2TB 970 NVME

### StartOS Version

0.3.4~3

### Client OS

Other

### Client OS Version

Pi

### Browser

Brave

### Browser Version

Tor Brave Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

### Current Behavior

Tried to upgrade to 0.3.4.4 from the UI via Tor from the system Tab. 

The error message in notifications:

Update was not successful because of Filesystem I/O Error: rsync error: 23 rsync: [sender] change_dir "/raspberrypi" (in 0.3.4.4) failed: No such file or directory (2) rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1865) [Receiver=3.2.7]

### Expected Behavior

Expecting it to Upgrade the OS

### Steps to Reproduce

Select the system tab.
Select Software Update.
Select "Begin Update"

**Comment by MattDHill** [comment]
You must have tried this within seconds of us launching it. The rasp Pi image has not fully deployed. Please try again

**Comment by Ven0r** [comment]
Yep you are correct! Talk about timing on my part.

**Comment by Ven0r** [comment]
Yep you are correct! Talk about timing on my part.
