### ISSUE TITLE
[bug]: Service stuck in "Paused" state after failed backup

### ISSUE THREAD

**Issue by Dominion5254** [Start9Labs/start-os#2388]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Server Pure

### StartOS Version

0.3.4.3

### Client OS

MacOS

### Client OS Version

Ventura 13.3.1

### Browser

Firefox

### Browser Version

115.0.3

### Current Behavior

If the backup target runs out of space, the OS provides a notification that the backup failed due to insufficient storage space. However, the service container that was being backed up remains in a "Paused" state.

### Expected Behavior

The service container that was in the process of backing up should be unpaused instead of hanging in a "Backing Up..." state.

### Steps to Reproduce

1. Create a backup to an external drive with insufficient space.
2. Observe service container that was backing up when the backup drive ran out of space remaining in "Paused" (Backing Up) state.

**Comment by dr-bonez** [comment]
#2094
