### ISSUE TITLE
[bug]: Services' LAUNCH UI button doesn't use https:// on .onion links when StartOS web-UI is loaded from https://*.onion

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/start-os#2413]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Server Pure

### StartOS Version

0344

### Client OS

Linux

### Client OS Version

Debian

### Browser

Firefox

### Browser Version

117

### Current Behavior

1. Even though links under Properties have been updated to be prefixed with https:// for .onion URLs, if one loads the StartOS web-UI via its .onion, clicking LAUNCH UI to visit those links still goes to http://servicehostname.onion

### Expected Behavior

Expect all service's Tor links to use https:// when the StartOS Web-UI is loaded over https://blahblah.onion

### Steps to Reproduce

Login to StartOS via https://blahblah.onion

Click the Vaultwarden LAUNCH UI button

**Comment by MattDHill** [comment]
1. Not all Tor URLs can be accessed over https. It varies from service interface to service interface.

2. There is nothing to be done about this in 0.3.x. The problem will not exist in 0.4.0.
