### ISSUE TITLE
[feat] Do Not Allow Backups of Services That Have Never Been Configured

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2417]
Currently backups of never configured services are allowed, and a restore of these services will result in the following error:

![image](https://github.com/Start9Labs/start-os/assets/39687477/e116c875-4dce-4aef-9db1-466aa30381f6)

**Comment by MattDHill** [comment]
Chnaging this ticket to continue permitting backups but to fix the restore flow

**Comment by MattDHill** [comment]
This is an issue with LND specifically. LND should be able to handle this situaiton.
