### ISSUE TITLE
[bug]: installation on raspi still encrypted

### ISSUE THREAD

**Issue by remcoros** [Start9Labs/start-os#2449]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Pi (8GB) / 32Gb SD / Samsung T7 SSD

### StartOS Version

v0.3.4.4-hotfix

### Client OS

Windows

### Client OS Version

Windows 11

### Browser

Chrome

### Browser Version

latest

### Current Behavior

According to the changelog of v0.3.4.4 installation on raspi should disable encryption:

- disable encryption for new raspi setups by @dr-bonez in https://github.com/Start9Labs/start-os/pull/2348

I installed (using the DIY tutorial) the latest image, but encryption is still enabled.

### Expected Behavior

Installing on a raspi should not enable encryption

### Steps to Reproduce

- Flash startos-0.3.4.4-9322b3d-20230810_raspberrypi.img.gz 
- Go through the installation procedure
- Found that LUKS is enabled on the data drive

### Anything else?

I found that this commit: 082c51109ddb8fd9f0577d783bbefb5e20cd617c (PR: #2373) removed the "build/raspberrypi/config.yaml" file, which has the setting "disable-encryption: true", but since this file does not exist, encryption is never actually disabled on a raspi.

**Comment by dr-bonez** [comment]
Yes, we elected to not include the change in 0.3.4.4, however we have disabled luks for raspberry pi in 0.3.5 along with several other performance improvements. This is managed within the https://github.com/Start9Labs/startos-image-recipes repository

**Comment by remcoros** [comment]
I see, thanks for the clarification 👍
