### ISSUE TITLE
[feat]: Check password lenght at setup

### ISSUE THREAD

**Issue by ademar111190** [Start9Labs/start-os#2454]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

I created a password bigger than 64 characters at setup time, but on the first login, I got an error saying the password needs to be smaller than 65 characters

I've tried the first 64 characters of my password and it works, but it is better to explicitly say it at password creation time that you have a limit of 64 characters.

### Describe the Use Case

Avoid user creating an invalid password

### Describe Preferred Solution

My preferred solution is do not limit the password lenght

**Comment by MattDHill** [comment]
This was fixed in 0.3.4.4. Can you confirm which version you were setting up?

**Comment by ademar111190** [comment]
> This was fixed in 0.3.4.4. Can you confirm which version you were setting up?

I don't have the file anymore so I can't confirm.
Looking to the system now, it is at `9322b3d07e39c0c3bbd1b63ef225b7a17f7b337d`; I haven't update it, so unless it automatically update itself that was the version I did use to set up

**Comment by ademar111190** [comment]
BTW I did use a password manager that input the whole password at once

**Comment by ademar111190** [comment]
I just flashed a new sdcard with the latest available image and the problem didn't happened.
i.e. I got a warning saying my password was too long; so probably I have used an old version.
