### ISSUE TITLE
[bug]:  Unable to Launch UI and access the app

### ISSUE THREAD

**Issue by YapWC** [Start9Labs/start-os#2542]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

HP Laptop with 500 HDD

### StartOS Version

0.3.5~1

### Client OS

Windows

### Client OS Version

Windows 11 Home 23H2

### Browser

Brave

### Browser Version

1.61.104

### Current Behavior

I am able to open and access the https://sleazy-mullets.local/home from home network. However when I tried to Launch UI of Nextcloud I get an error as shown below. Same goes to when I try to Launch UI for File Browser app.

<img width="958" alt="image" src="https://github.com/Start9Labs/start-os/assets/34093361/84b9c208-624d-4c60-be73-e89edac4ce6b">

Additional info: Using Tor Browser is fine.

### Expected Behavior

Able to Launch UI for app that had been installed from local network without using Tor Browser.

### Steps to Reproduce

1. Login into your Start9 OS account.
2. Launch UI for NextCloud.

Do it from Client Laptop.

**Comment by MattDHill** [comment]
Did you follow the "Connecting Locally" guide and troubleshooting from our docs?

Given that you are using Windows, my guess is you have Bonjour problems. See here: https://docs.start9.com/0.3.5.x/user-manual/connecting-lan#windows-only
