### ISSUE TITLE
[bug]: Update failing 

### ISSUE THREAD

**Issue by jwilkins** [Start9Labs/start-os#2615]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

embassy one

### StartOS Version

0.3.4

### Client OS

MacOS

### Client OS Version

14.2

### Browser

Firefox

### Browser Version

124.0.2

### Current Behavior

Updates fail with the following error:

Update was not successful because of Filesystem I/O Error: rsync error: 10 rsync: [Receiver] failed to connect to registry.start9.com (45.55.33.39): Connection refused (111) rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3] 

### Expected Behavior

system should update to 3.5.x

### Steps to Reproduce

System->Software Update->Begin Update

**Comment by MattDHill** [comment]
We've seen some weirdness with our registry over the past week that only seems to affect certain users. Hopefully this has resolved itself for you. If not, you may need to flash update to the latest version of StartOS. We will be making a major update to the Registry in the near future that will hopefully resolve this permanently.
