### ISSUE TITLE
[bug]: front end versioning display discrepancy when there's a leading 0 of minor version number

### ISSUE THREAD

**Issue by stupleb** [Start9Labs/start-os#2624]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

All

### StartOS Version

0.3.5.1

### Client OS

MacOS

### Client OS Version

N/A

### Browser

Firefox

### Browser Version

N/A

### Current Behavior

<img width="305" alt="sos1" src="https://github.com/Start9Labs/start-os/assets/130350501/4150ce5a-2c1d-43ca-80a0-d19a39c69ce3">
<img width="276" alt="sos2" src="https://github.com/Start9Labs/start-os/assets/130350501/543eee4e-31c5-46d7-b695-fc936715c24d">

Leading zeros are displayed in some locations in StartOS, but not in some others. The lack of consistency means that at a glance the versions feel very distinct. 

### Expected Behavior

Display consistently.

### Steps to Reproduce

Install a service
Install another that has the first as a dependency

**Comment by MattDHill** [comment]
@dr-bonez code to display version below.

```
export function displayEmver(version: string): string {
  const vs = version.split('.')
  if (vs.length === 4) return `${vs[0]}.${vs[1]}.${vs[2]}~${vs[3]}`
  return version
}
```

Clams manifest looks correct: https://github.com/clams-tech/clams-remote-startos/blob/master/manifest.yaml#L103

The leading "0" appears to be srtipped before reaching the FE.

**Comment by dr-bonez** [comment]
The current emver specification doesn't actually support leading zeros, so it's stripped when the version is parsed. This will be accounted for in the new specification.

**Comment by MattDHill** [comment]
Leading zeros will not be supported by exver. The discrepancy shown in the image above will be resolved by neither having a leading zero. This means the upstream version of a package may look differently than otherise published by that team, but semantically it will behave the same.
