### ISSUE TITLE
[bug]: Invalid Package Type

### ISSUE THREAD

**Issue by jbdatko** [Start9Labs/start-os#2735]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already report this problem.

### Server Hardware

Beelink type x86

### StartOS Version

latest -- idk start9 says no updates? How do I tell?

### Client OS

Windows

### Client OS Version

11

### Browser

Firefox

### Browser Version

latest no updates but I've tried multiple browsers

### Current Behavior

I'm (and at least one other) are having trouble side loading albyhub. We download it from the github and then we try to sideload it, and it says invalid package type (https://github.com/horologger/albyhub-startos/issues). I don't even know how to start to debug this, I couldn't find any logs. Multiple people seem to be installing this just fine.

### Expected Behavior

Sideloading should work.

### Steps to Reproduce

Download albyhub from their github (https://github.com/horologger/albyhub-startos/actions/runs/10852287383/artifacts/1930668742) and sideload it. It fails for me.

**Comment by MattDHill** [comment]
Closing here as this is not a StartOS issue. The issue you created in Alby Hub should suffice.
