### ISSUE TITLE
[bug] Health checks displaying incorrect response

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#2755]
Both the format and message of non-standard health checks (ones that use bash scripts instead of the standard JS health checks) appear incorrect.

<img width="1723" alt="Screenshot 2024-10-15 at 4 53 07 PM" src="https://github.com/user-attachments/assets/e2b921d0-fdd9-4b9b-af77-0e064d049d42">
<img width="1489" alt="Screenshot 2024-10-16 at 11 22 39 AM" src="https://github.com/user-attachments/assets/7c4b7c5e-7742-4ce5-b639-1c7056bb3b5f">

**Comment by dr-bonez** [comment]
fixed in https://github.com/Start9Labs/start-os/pull/2759
