### ISSUE TITLE
[bug] Dependency not showing as dependnency

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#2756]
Since dependencies are not showing, making an action request results in the following console error:

Example case is mempool installed from alpha on this [image](https://github.com/Start9Labs/start-os/actions/runs/11352205323).

<img width="1494" alt="Screenshot 2024-10-16 at 11 31 34 AM" src="https://github.com/user-attachments/assets/badbf2aa-3f33-41ef-9852-1c8fce7cfaab">

**Comment by MattDHill** [comment]
You can't run an action against Bitcoin if Bitcoin is not a dependency. The screenshot shows that it is not a dependency.

So the actual bug is that Bitcoin should be showing as a dependency

**Comment by MattDHill** [comment]
Updated the title to reflect the bug

**Comment by elvece** [comment]
More details from patchdb:

<img width="1496" alt="Screenshot 2024-10-16 at 4 17 11 PM" src="https://github.com/user-attachments/assets/953af4c1-5cab-4a9b-afef-6903da16ca16">
