### ISSUE TITLE
Improve Bitcoin Properties tab

### ISSUE THREAD

**Issue by copy2018** [Start9Labs/start-os#2792]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/start-os/issues) that already suggest this feature.

### Describe the Feature Request

I have modified the main.rs to improve Properties tab for the bitcoin core wrapper and submitted a PR about a week ago and would be grateful if someone could get around to checking it. I have already built and tested it to ensure it works properly and have included a screenshot of what the updated code looks like.

Link to PR: https://github.com/Start9Labs/bitcoind-startos/pull/154

### Describe the Use Case

Properties added for added convenience:

1. REAL Max Mempool Size in MB given core's overhead and safety buffer
2. Current Mempool Usage in MB and as a percentage
3. Mempool Transaction Count
4. Progress to next halving added (counts in years, days, hours, mins)
5. Node uptime since service was started
6. Current total supply of Bitcoin based on issuance schedule (may be very slightly inaccuate compared to gettxoutsetinfo but is great for monitoring at a glance without needing to wait)

I also consolidated the blockchain sync summary to one line to save screen real estate.

Here is an image of what it looks like:
![image](https://github.com/user-attachments/assets/f3e94aba-cc8c-47c7-b4da-e815a13922a5)

### Describe Preferred Solution

Link to PR: https://github.com/Start9Labs/bitcoind-startos/pull/154

### Describe Alternatives

Reasons 'total bitcoin supply' may not be exactly the same as gettxoutinfo:

- Varied Inputs and Outputs: The total amount shown represents all unspent coins across all outputs, which includes not only block rewards but also many user transactions, each with its unique input and output values. These transactions may not align with exact multiples of the block reward.
- Fee Distribution: Transaction fees also contribute to the total amount but are not typically set to neat multiples. They are instead dynamic values determined by users and miners, so they add irregular values to the total supply.
- Decay in Reward Structure: If you're working within a system where block rewards decrease over time, previous block rewards might have been higher or lower than 3.125, meaning historical outputs would still affect the total.
- Fractional Accumulation: With every transaction and UTXO creation, there could be small rounding effects or dust amounts, which, over thousands of transactions, contribute to a value that doesn't perfectly align with any specific multiple.

However overall this is a great at a glance metric imo to keep a check on things (with a fraction of a percent difference), especially since gettxoutsetinfo is resource and time intensive.

**Comment by MattDHill** [comment]
@copy2018 thank you for the request. Please re-create this ticket in the [Bitcoin service repository](https://github.com/Start9Labs/bitcoind-startos), as it is not a StartOS issue.
