### ISSUE TITLE
Make install progress visible from the CLI

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/start-os#519]
It would be nice to know what the install progress was even in a CLI context

Reported by @chrisguida

**Comment by chrisguida** [comment]
nifty progress bar lib https://github.com/mitsuhiko/indicatif

**Comment by mirkoRainer** [comment]
The install progress of what?

**Comment by chrisguida** [comment]
@mirkoRainer installs

**Comment by mirkoRainer** [comment]
Am I correct in assuming that `backend->src->install->mod.rs->cli_install` would be an appropriate place to monitor the progress? Or maybe `Line 125` `pub async fn install`? 

It seems like there are two ways of installations, `package.sideload` and `package.install`. 

I assume that `package.install` is the one to focus on.

If I'm in the right place, I assume that the progress bar would be external to this code but would be triggered concurrently while awaiting the `cli_install` code?
I'm also going to have to read up on and understand more about what 
```rs
#[command(
    custom_cli(cli_install(async, context(CliContext))),
    display(display_none)
)]
#[instrument(skip(ctx))]
pub async fn install(
```
does. And perhaps that will help me decide where to start.

The more I read this, the more I'm inclined to think the progress bar will be an async tokio call within `install`?

fwiw, I'm new to Rust with little practical application so thank you in advance for fielding my questions.

**Comment by ProofOfKeags** [comment]
Both would be nice actually. Sideloading refers to when you are installing a .s9pk that you have locally vs from a marketplace.
