### ISSUE TITLE
Setup Wizard -redesign final step

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/start-os#643]
- Redesign page

- Add LAN info, including SSL Cert download and instructions.

**Comment by ProofOfKeags** [comment]
We may need to include a significant wait time for this to work. From my observation the final screen that renders the tor address completes long before

1. The tor address is capable of servicing traffic
2. The lan address has been published over mdns.

As such there may be backend work that needs to go into supporting this. It all depends on the desired UX though. @MattDHill if you have input into what the UX during this wait time ought to be (assuming it is unavoidable) please provide some of that here.
