### ISSUE TITLE
Auto-configure button not working

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#676]
Clicking "auto-config" does literally nothing - no errors, no requests, no action :(

The first screenshot displays with the console package-data for lnd and the second with pacakge-data for proxy.
<img width="1668" alt="Screen Shot 2021-10-13 at 6 19 40 PM" src="https://user-images.githubusercontent.com/12953208/137231068-282e6b40-cae7-4c17-b6e4-3fe457b5fbe1.png">
<img width="1675" alt="Screen Shot 2021-10-13 at 6 17 13 PM" src="https://user-images.githubusercontent.com/12953208/137231071-a3409ff4-0436-4c3e-8cfc-990e8944e2e8.png">

**Comment by MattDHill** [comment]
This is the result of the UI blowing up due to an underlying type mismatch between FE and BE. See #674.
