### ISSUE TITLE
Error when selecting "disabled" for error bug reporting.

### ISSUE THREAD

**Issue by elvece** [Start9Labs/start-os#701]
This happens on the initial modal for enabling/disabling bug reporting.

**Comment by ProofOfKeags** [comment]
Looks like we hadn't encountered this before. There isn't a lot of rhyme or reason to when revisions are returned vs when they aren't from my POV so it is commonly overlooked. I will fix this. But there are a couple of other issues with this feature that I think need to be ironed out.

1. Documentation link doesn't actually elucidate the issue
2. At present we do not report generic error codes, we report log messages that are `warning` or `error`
3. We do not report these over Tor as of right now.
