### ISSUE TITLE
[feat]: new Server Status "Shutting Down / Restarting"

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/start-os#953]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

The minimum time to shut down Embassy is always the longest sigterm-timeout of its services. Yet the shutdown/restart endpoints are synchronous. As such, the user can be left looking at a blocking spinner for multiple minutes while Embassy shuts down. Also, refreshing the page during the request could case undesirable behavior. I believe this warrants a new server status of "Shutting Down".

### Describe the Use Case

User clicks Shutdown/Restart, and instead of getting a blocking spinner, they will be directed to a special page/modal that displays the shutdown progress of each service, similar to the experience of server backups. The user would not be able to leave this page, even upon refresh.

### Describe Preferred Solution

1. Convert shutdown/restart endpoints to async
2. Add "shutting-down" status to ServerStatus enum
3. continue to report revisions during shutdown process
4. FE will direct user to special page where they can observe the shutdown process
5. When final service completes its stop sequence, FE will display a "shutdown complete" message and continue polling as usual. If the Embassy comes back up, it will be in "Running" status, which will cause the FE to direct back to the normal experience.

**Comment by chrisguida** [comment]
I also noticed that the shutdown sound never plays. Should I create a new issue for that?

**Comment by ProofOfKeags** [comment]
What is the maximum time it can take for the server to shut down? If it is sufficiently long we should give feedback both when the request is accepted and before the box goes down.

**Comment by dr-bonez** [comment]
if there are no deadlocks, can take as long as the longest sigterm-timeout. If there is a deadlock, obviously it can take forever

**Comment by chrisguida** [comment]
I've rarely had shutdown complete faster than a few minutes, and I've never actually heard the shutdown noise play. The only time it shuts down in under 5m is when there are no services running and few services installed. About half the time it hangs indefinitely

**Comment by chrisguida** [comment]
@MattDHill Do you want me to create a new issue?

**Comment by MattDHill** [comment]
Yes please. This is a feature request. If there's a bug with shutdown, it needs to be a P1 ticket.

**Comment by elvece** [comment]
Need both shutting down and restarting state. FE will have an overlay greying out background. FE needs to be careful about state synchronization, don't show status of service until it has gotten a patch - apply the patch before it says reconnected. 

Bug in patch db: UI will only update the connection status when a new patch comes in. Switch this knowledge to patch db if we are connected at all. Each source will need to track itself, so it can be picked up by in UI. 

A successful websocket or polling should set the status connection to true. As soon as a poll succeeds, try to switch back to websockets.

**Comment by k0gen** [comment]
Also, we shouldn’t allow users to interact with StartOS UI after clicking RESTART
![Screenshot 2023-06-21 at 12 34 39](https://github.com/Start9Labs/start-os/assets/3606313/1f546223-cd96-4288-acaa-677d6389a479)
I suggest that after clicking restart the screen should be locked with a progress bar indicating that the server is restarting.

We can go safe with something like that:
![loading-wheel-3071370727](https://github.com/Start9Labs/start-os/assets/3606313/7663dc95-6199-4236-8ccc-c882872b1656)
Go bold with something more like this:
![reboot](https://github.com/Start9Labs/start-os/assets/3606313/b804817a-5bf8-4a5e-98e0-87b3673e7a13)
![tenor](https://github.com/Start9Labs/start-os/assets/3606313/eb196f5b-6685-4b9b-9d68-201058fed3a9)
![tenor-2](https://github.com/Start9Labs/start-os/assets/3606313/681402e7-199f-4421-b146-a15d2ff5681e)
Or something funny like this:
![progress_bar_viii-3038524224](https://github.com/Start9Labs/start-os/assets/3606313/5b05a125-2fdb-4320-b34a-48942f1d62c0)
