### ISSUE TITLE
[feat]: Put service in "restarting" status when user saves config, as on 0.2

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/start-os#958]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Put service in "restarting" status when user saves config, as on 0.2

### Describe the Use Case

Currently in 0.3, when the user saves a config, the service does not indicate to the user that it is restarting. This can lead to confusion if, for example, bitcoind takes a long time to restart because it is flushing the utxo cache to disk. The service simply appears to lose all functionality, while the package details page shows that everything is fine.

### Describe Preferred Solution

Put service in "restarting" status when user saves config, as on 0.2

**Comment by dr-bonez** [comment]
given that this is non-trivial, I would like to mark as p2 and punt to 0.3.1. @MattDHill please advise

**Comment by chrisguida** [comment]
It might help to implement a "suppress notifications" feature: https://github.com/Start9Labs/bitcoind-wrapper/issues/27#issuecomment-996158563 to have a "restarting" backend status

**Comment by MattDHill** [comment]
Can you catch me up on how suppressing notifications in certain circumstances is an alternative solution to implementing a "restarting" status for services?

**Comment by chrisguida** [comment]
It's not an alternate solution, it might help in the implementation. If the backend can see that a service is restarting, it will know when to suppress notifications.

**Comment by ProofOfKeags** [comment]
Is the original ask then to suppress notifications or is the status itself important *in its own right*

**Comment by dr-bonez** [comment]
we should not suppress notifications. but it should be possible to have a status for when the app is running but it is between its most recent exit and its next restart

**Comment by chrisguida** [comment]
@ProofOfKeags the original ask is to implement the restarting status, as seen on 0.2.x. If you go to 0.2.x and save a config, you will see this behavior. On 030, in contrast, the service simply appears to be running. This is very confusing.

**Comment by dr-bonez** [comment]
connected to #1304, would like to add a `configuring` status

**Comment by elvece** [comment]
> #1304

Is this status still relevant with the emergence of JS procedures?

**Comment by elvece** [comment]
Also, are we going to cascade stop / start dependent services? In other words, what is the proposed solution for the slew of notifications that will happen upon restarting a service with many higher dependents eg. bitcoind)

**Comment by MattDHill** [comment]
Can this be closed @dr-bonez ?

**Comment by dr-bonez** [comment]
This is addressed in refactor/gut-config which hasn't been merged

**Comment by MattDHill** [comment]
addressed in 035, service will enter stopping, then starting
